### PR TITLE
Raw high lat v2

### PR DESCRIPTION
**Pull request by ZhuxiaoLi66**
Added the new features (physics codes) to let WAM driver parameters to drive WAM by reading Adam's driver parameter files. 
a) for WAM run with varying kp, f107, kpa, f107a, hp, hpi is o.k.
b) for the run with solar wind parameters (for prep_weimer), the code is no problem to get the parameters in, while the run will crash.     
c) As a result, we set 'SWIN' (switch to use observational solar wind drive parameters) into false by default for now.   
d) we fixed the problem for the run with Solar wind parameters. After the final check, it should be ready to pull.

### CODE REVIEW

**Comment by ZhuxiaoLi66** [comment]
@akubaryk please double check my revise in ./scripts/compsets/exglobal/exglobal_fcst_nems.sh
I added one line 'export F107_KP_DATA_SIZE=$((LEN_F107-5))' to avoid WAM can only read one hour input from the parameter file. Thank you.

**Comment by akubaryk** [comment]
The change to exglobal_fcst_nems.sh is good; should have been there from the start.

**Comment by joeschoonover** [comment]
Running this branch this morning - I'll have model output from a coupled run for us to review this afternoon

**Comment by joeschoonover** [comment]
5 day simulation output required

**Comment by joeschoonover** [comment]
Because @weiyuyang1234 pushed a bunch of commits to raw_high_lat_v2, we can no longer merge this branch into development --raw_high_lat_v2 no longer accurately reflects the description of this pull request.

**Comment by weiyuyang1234** [comment]
Joe,

Please tell me what I should to do?

Weiyu

**Pull request closed without merging**
