### PR TITLE
Introducing ability to fill empty regions in IPE magnetic grid

### PR DESCRIPTION
**Pull request by rmontuoro**
This PR introduces the following features in the NUOPC cap for IPE:

- Ability to fill empty polar and equatorial regions in IPE magnetic grid (mesh) by setting the new `mesh_fill` namelist variable to 1. Equatorial regions are filled with additional cells defined via existing grid points, while new polar nodes are created at each grid height by geometrically averaging neighboring nodes to support additional filler cells. Filling is done by default (`mesh_fill=1`); this behavior can be changed by setting the value of `mesh_fill` to 0 in IPE's input namelist file (`IPE.inp`):
```
&ipecap
  ...
  mesh_fill = 0
  ...
/
```
Note that the current default value for `mesh_height_max` (782 km) may also need to be increased in ``&ipecap`` to extend the magnetic grid height if its upper region further requires filling. See Issue #192 for details.

- Improved halo exchange in IPE mesh creation
- Error logging restored if field checking is enabled
- Debug output restored for IPE mesh decomposition across PETs

One bug fix and updated regridding settings are also introduced in the SWPC mediator, while a no longer required initialization phase is removed.

### CODE REVIEW

**Comment by rmontuoro** [comment]
Pushed two additional updates to:

- Set the new SWPC mediator as default in coupled compset configuration file (`scripts/compsets/config/coupled.config`)

- Removed obsolete specialization of NUOPC initialization phase `IPDv03p4` in previous Spaceweather mediator. This specialization method (`InitializeP4`) was used to redistribute field data imported from IPE over the mediator's PETs, if different from IPE's PET list. Since ESMF version 7.1.0r, this task is performed by standard NUOPC Connectors using a more accurate implementation.

**Comment by rmontuoro** [comment]
**How to test this PR:**

1. Clone the WAM-IPE repository, if needed
```
git clone https://github.com/SWPC-IPE/WAM-IPE.git
cd WAM-IPE 
```
2. Checkout the `development` branch
```
git checkout development
git pull (if needed)
```
3. Merge with `origin/two_way_dev`:
```
git merge origin/two_way_dev
```
The merge will occur automatically.

4. Edit `scripts/compsets/coupled_20130316.config` to setup a 24-hour coupled test run as follows:
```
export JOBNAME=pr_290_merged
...
export FHMAX=24 # hours to forecast from input files. think of this as a segment length
export FHRES=24 # hours between writing restart files
```
You may also experiment with different IPE horizontal decompositions. For instance:
```
export NPROCIPE=$((4*20))
export IPEDECOMP="4 20"
```
and/or by assigning different numbers of PETs (parallel tasks) to each of the other components, _e.g.:_
```
export NPROCGSM=64
export NPROCMED=80
```

5. Submit your test run:
```
cd scripts/compsets
./submit.sh coupled_20130316.config
```

6. In a *different* directory, repeat steps 1, 2, and 4 (skip the merge) to submit an identical test run for the HEAD of the `development` branch (your reference)

7. Add the following line to `coupled_20130316.config` to select the new SWPC mediator (it is the default in `two_way_dev`)
```
export med_model=swpc
```
and change the job name:
```
export JOBNAME=pr_290_reference
```

8. Submit your test run as in step 5

9. Compare output from this run (step 8) and your previous run (step 5).


***Note:*** The two 24-hour runs generated bitwise identical output files on Theia.

**Comment by akubaryk** [comment]
On the basis of bitwise identical results for a standard configuration on Theia, and a level of comfort with the simple changes to the run scripts, I am approving this PR. Would be happy to merge this with one more positive review from @joeschoonover or @IonospherePlasmasphereElectrodynamics.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
@rmontuoro , 

Thanks for your very detail instruction. I was able to merge, build, and submit the 2 jobs(with vs. without merge). And @akubaryk , thanks for converting the script to slurm. I am going to report the results as soon as the runs have been completed.
Thanks.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi @rmontuoro ,

great news!
my two tests before vs. after merge were confirmed bitwise identical. 
Just in case, I submitted 2 more tests:(1) a different IPE layout: 40x16; (2) Mesh_height_max=1002.(original=782.)
I will let you know as soon as these tests are completed.
Thanks for your patience.
Naomi

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi @rmontuoro ,

In the test (2) Mesh_height_max=1002.(original=782.), 
the ipe result (ipe_grid_plasma) was not confirmed bitwise identical.
at the next step, I am going to investigate how big the differences are, by visualizing the data.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi @rmontuoro again!


In the test (1) (1) a different IPE layout: 40x16,
the ipe result (ipe_grid_plasma) was not confirmed bitwise identical. 

the great news is that the 24hr run with the new 40x16 layout took 4378s, which is 8sec faster than the default run (the default 24hr run with the 58x8 layout took 4386s).

at the next step, I am going to quantify the differences, by visualizing the data.

**Comment by akubaryk** [comment]
Simply updated this branch with the latest commit to development to address the restart bug. @IonospherePlasmasphereElectrodynamics is there any follow-up on your above comments? @rmontuoro will be out of office for three weeks at the end of this week, so we would like to either merge this or get feedback if we think any further changes or testing is needed.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
@akubaryk,

Thanks for your reminder. I agree with you that we should update this branch with the latest commit as soon as possible.

Here is a TEC comparison plot between 3 test runs:
(top)before PR#290
(middle)after PR#290 with default IPE layout, 58x8
(bottom)after PR#290 with modified IPE layout, 40x16
Screen Shot 2019-06-03 at 12 15 44



The comparison shows that the 40x16 test run appears to be visually identical to the two 58x8 runs, suggesting that the 40x16 run was successfully finished.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Here is another TEC comparison plot at 1hr into the simulation between 2 test runs:
(top)before PR#290
(bottom)after PR#290 with Mesh_height_max=1002.(original=782.)
.
Screen Shot 2019-06-03 at 12 28 37


The comparison clearly shows that the test run with Mesh_height_max=1002 has something wrong. One possibility is that the way I modified the Mesh_height_max was incorrect. I strongly suggest that somebody else ( preferably @rmontuoro ) tries to do a similar test to see if the same feature can be reproduced.  
Thanks.

**Comment by akubaryk** [comment]
We have agreed to merge this PR, and @IonospherePlasmasphereElectrodynamics will open a new issue for the `mesh_height_max` issue noted above.

**Pull request merged**
