### PR TITLE
Fix for physics timestepping

### PR DESCRIPTION
**Pull request by akubaryk**
Forcing nsphys=1 in gloopb.f allows...
  * kdt=1: dtp=180, dtf=180 (no change)
  * kdt>1: dtp=360, dtf=180 (idea_phys uses dtp=360 instead of dtp=180, gbphys is called once w/ dtp=360 instead of twice w/ dtp=180)

This brings the idea_phys tendency updates in line with the intended physics time-stepping scheme. See #252 for more info and some figures detailing the issue/proposed resolution. If anybody would like to see more runs with other initial conditions, please let me know. We can create new issues out of this PR if needed.

### CODE REVIEW

**Comment by ZhuxiaoLi66** [comment]
wam_2d_129lev_200km_t_2013041506_nodamping_nsphys1_check
wam_2d_129lev_200km_t_2013041512_nodamping_nsphys1_check
wam_2d_129lev_200km_t_2013041518_nodamping_nsphys1_check
wam_2d_129lev_200km_t_2013041500_nodamping_nsphys1_check

**Comment by ZhuxiaoLi66** [comment]
This is the similar plot with above ones while for Mean Mass on 2013041500. 

wam_2d_129lev_200km_mms_2013041500_nsphys1_check

**Comment by ZhuxiaoLi66** [comment]
temp_profiles_201304_wam_nsphys1_wam_tip_msis
temp_profiles_201307_wam_nsphys1_wam_tip_msis
temp_profiles_201310_wam_nsphys1_wam_tip_msis
temp_profiles_201401_wam_nsphys1_wam_tip_msis

**Comment by ZhuxiaoLi66** [comment]
Above plots are monthly mean plots based on annual run with fixed F107 and Kp.

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,
looks good. Slight changes in global mean temperature, as expected, but not
too extreme.
We will wait to see other plots before deciding on re-tune strategy.
Tim

**Comment by ZhuxiaoLi66** [comment]
The following plots are validation of nsphys1 in seasonal variation at different T and composition perspectives.
number_density_201304_6hrly_nsphys1
number_density_201401_6hrly_nsphys1
number_density_201307_6hrly_nsphys1
number_density_201310_6hrly_nsphys1

**Comment by ZhuxiaoLi66** [comment]
Seasonal variation in WAM zonal mean Temp by WAM nsphys1, tip and MSIS. 
monthly_zonal_mean_t_wam_msis_f107_120_201401_nsphys1_tip
monthly_zonal_mean_t_wam_msis_f107_120_201310_nsphys1_tip
monthly_zonal_mean_t_wam_msis_f107_120_201307_nsphys1_tip
monthly_zonal_mean_t_wam_msis_f107_120_201404_nsphys1_tip

**Comment by ZhuxiaoLi66** [comment]
Seasonal Variation of horizontal O/N2 distribution at WAM Lev135. 
o_to_n2_0ut_wam_msis_f120_kp3_135lev_201401_nsphys1_tip
o_to_n2_0ut_wam_msis_f120_kp3_135lev_201310_nsphys1_tip
o_to_n2_0ut_wam_msis_f120_kp3_135lev_201307_nsphys1_tip
o_to_n2_0ut_wam_msis_f120_kp3_135lev_201304_nsphys1_tip

**Pull request merged**
