### PR TITLE
8th order diffusion

### PR DESCRIPTION
**Pull request by akubaryk**
The variable "jdel" controls the order of the diffusion in the dynamical core. (Re-)increasing it to 8 produces the desired result of mid-wavenumber (20-30) variability in the upper levels of the model, specifically around 200km.

With #265 we have a number of temperature/wind verification videos in terms of wavenumber variability under quiet and storm conditions (2d plots of a specific model level), as well as checks on stability through longer runs going through storm response, but we need to perform verification of zonal mean temp/winds, composition, and more specific tropospheric verification in order to bring this into development.

I will work on the tropospheric verification (global mean by-level seeking to resolve cold bias in current development branch compared to WSM). Zhuxiao, please plan to perform whatever remaining upper atmosphere (composition) verification needs to be done to bring this into development.

### CODE REVIEW

**Comment by ZhuxiaoLi66** [comment]
monthly_zonal_mean_mms_wam_nsphys1_msis_2013_1_jdel8_jdel4_5p
monthly_zonal_mean_mms_wam_nsphys1_msis_2013_4_jdel8_jdel4_5p
monthly_zonal_mean_mms_wam_nsphys1_msis_2013_7_jdel8_jdel4_5p
monthly_zonal_mean_mms_wam_nsphys1_msis_2013_10_jdel8_jdel4_5p
monthly_zonal_mean_t_wam_nsphys1_msis_f107_120_201304_jdel8_jdel4_5p
monthly_zonal_mean_t_wam_nsphys1_msis_f107_120_201307_jdel8_jdel4_5p
monthly_zonal_mean_t_wam_nsphys1_msis_f107_120_201310_jdel8_jdel4_5p
monthly_zonal_mean_t_wam_nsphys1_msis_f107_120_201401_jdel8_jdel4_5p
t_wind_2d_wam_nsphys1_msis_f120_kp3_135lev_201401_jdel8_jdel4
t_wind_2d_wam_nsphys1_msis_f120_kp3_135lev_201310_jdel8_jdel4
t_wind_2d_wam_nsphys1_msis_f120_kp3_135lev_201307_jdel8_jdel4
t_wind_2d_wam_nsphys1_msis_f120_kp3_135lev_201304_jdel8_jdel4

**Comment by akubaryk** [comment]
Thanks for the figures Zhuxiao. Do you think the slight changes in temp and composition are acceptable (and if not, can they be addressed with the JH tweaks)?

Theia will be down tomorrow but I will be able to provide the tropospheric verification on Wednesday... early indications are good on that front.

**Comment by ZhuxiaoLi66** [comment]
Hi Adam, the slight changes are acceptable, the tropospheric verification will also be very helpful. There is an over heating issue during storm time in 2013030317 storm run with this version as also indicated in your video, while it seems not triggered by jdel8 setting, it exists in nsphys1 version also. I am investigating this issue, while I don't think it will influence the merge of jdel8 version to development. What is your idea, Tim?

**Comment by timfullerrowell** [comment]
This is a great set of validation figures, Zhuxiao.
Just what we need routinely after any change.
I think the minor changes with del8 are acceptable.
I agree the storm response is probably not related to del8 and is an
ongoing activity.
I will be back in on Monday.
Hope all is well in Boulder.
Tim

**Comment by ZhuxiaoLi66** [comment]
Tim, thanks for the great response. talk with you next week!

**Comment by akubaryk** [comment]
for reference, this is the issue we had with the *current* development branch (bright blue line is the relevant comparison here):
vprof_t_l64_quad

Note the persistent ~1% cold bias between model levels 10-40 (900mb to 70mb roughly).

And the new result (sorry about the slower cadence):

vprof_t_l64_jdel8tropo

Not perfect, but this is a great improvement in the troposphere.

**Comment by ZhuxiaoLi66** [comment]
Adam, thanks for the update.  one question, in the upper panel,  the bright blue line indicates WAM dev_tip after nsphys1?

**Comment by akubaryk** [comment]
Yes, but the differences in the upper atmosphere may be due to unbalanced initial conditions and should be disregarded, if that's what you were looking at.

**Comment by ZhuxiaoLi66** [comment]
Adam, I think the JDEL8 setting is ready to be merged into development, you want to do that? thanks.

**Comment by akubaryk** [comment]
I am in favor but I need you or @timfullerrowell to submit an approved review before the merge can occur.

**Comment by ZhuxiaoLi66** [comment]
Adam, would like you know that I added my review, it seems the merge is ready to go. I think Tim also agree the merge.

**Comment by ZhuxiaoLi66** [comment]
Thanks, Adam. 
The JDEL8 is numerically advanced and I believe it improves the WAM physics at many aspects.  While  maybe we need to go back to NSPHYS1 version when we investigate the high storm temp. issue for simplify the problem.

**Pull request merged**
