### PR TITLE
Rc0.0.2 wcoss build changes

### PR DESCRIPTION
**Pull request by schoonovernumerics**
Theis merge will bring in Adam's changes to allow porting onto wcoss. These features have not been tested and documented on wcoss, but the CompSetRunNew scripts and IPE Standalone run as expected on theia. I have no issues with bringing this into development.

### CODE REVIEW

**Comment by akubaryk** [comment]
The changes in this branch are specifically to get WAM-IPE compiled on WCOSS without affecting Theia at all. George and I have a separate set of cold-start/restart compset scripts which run on WCOSS that are not in this set of changes, but I would propose that we do not worry about merging a new set of scripts that will be replaced in short order.

**Comment by schoonovernumerics** [comment]
So, are we not merging this branch yet ?

**Comment by akubaryk** [comment]
If the intention was to -- as soon as possible -- have something that builds AND (specifically) runs on WCOSS, then I should include George's compset files. If it can wait a week, then I'd like to commit something bigger with the scripting overhaul.

**Comment by schoonovernumerics** [comment]
I'll leave this to your discretion. I've checked out the branch on theia and all works. We can leave the pull request open until you make all the changes you want. Just notify us when you're ready. I'll help re-test out the code on Theia

**Comment by akubaryk** [comment]
Gonna merge this as-is, as I think just having the build system working on WCOSS is relevant to Houjun.

**Comment by schoonovernumerics** [comment]
Go for it. merge it in

**Pull request merged**
