### PR TITLE
Fixed input parameters

### PR DESCRIPTION
**Pull request by akubaryk**
This pull request is for changes to the pre-processing scripts that create the geomagnetic and solar wind input file `wam_input_f107_kp.txt`.

## New features

The branch adds two primary features, introducing an environment variable `INPUT_PARAMETERS` that is defined in `user.config`:
- Option to specify the geomagnetic drivers as fixed values, with a further option to either fix the solar wind drivers (`INPUT_PARAMETERS=fixall`) or algorithmically derive them using @timfullerrowell's [equations](https://github.com/SWPC-IPE/WAM-IPE/issues/126#issuecomment-374304207) (`INPUT_PARAMETERS=fixderive`). This solar wind driver derivation can also be done from the time-varying, observed F10.7/Kp values (`INPUT_PARAMETERS=timederive`). The "old" default option -- to run from the full historical observational database (`INPUT_PARAMETERS=timeobs`) -- is maintained, while `fixderive` is the new default, with F10.7=120.0 and Kp=3.0.
- Support for realtime .xml file parsing (`INPUT_PARAMETERS=realtime`). `exglobal_fcst_nems.sh` will default to the wam_input_new-* files if available, otherwise falling back on the traditional wam_input-* format, which does not have 24hr average Kp and time-varying F10.7d. Solar wind drivers are derived in all realtime runs, as a database from SWPC's realtime solar wind data has not yet been constructed.

Information on each option has been added to the two standard `*.config` scripts in `scripts/compsets`.

While I have confirmed the output from the parsing script for each `INPUT_PARAMETERS` configuration, we need to make sure that the namelist configuration is correct -- i.e., that WAM and IPE are receiving the values that we expect. If we need to extract the `RT_WAM/*_in` namelist configurations into `exglobal_fcst_nems.sh`, that should be done before we merge this pull request.

## Future work
Remove the unnecessary switches in WAM for specifying the solar and geomagnetic drivers.

### CODE REVIEW

**Comment by joeschoonover** [comment]
Compiling and beginning the 5 day run today for review

**Comment by joeschoonover** [comment]
Currently receive the error : 
```
checking IPEDECOMP against NPROCIPE: (x)
   bad IPEDECOMP, must be two space-separated integers! exiting.
```
when attempting to submit a job with either user.config or march2013_regression.config

**Comment by akubaryk** [comment]
One of the commits yesterday contained some unfinished code intended for a different branch; `git pull origin fixed_input_parameters` to resolve the issue.

**Comment by joeschoonover** [comment]
Looks like it got into the queue with that fix. Thanks

**Comment by joeschoonover** [comment]
I have set up the march2013_regression.config script to run the model for 24 hours. I'm trying to get out to five days; for some reason, the code crashed in the middle of the 3rd day.

The starting cdate is 2013031600; I want to pickup from 2013031800. To do this, I tried

`./submit.sh march2013_regression.config 3 5`

to start the simulation from the 3rd cycle. I've received the following output : 

```
searching ROTDIR, then RESTARTDIR, then IPE_IC_DIR for ipe_grid_*_params*201303190000
ls: cannot access /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/pr154_5day/ipe_grid_*_params*201303190000: No such file or directory
ls: cannot access /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/pr154_5day/restart_directory/ipe_grid_*_params*201303190000: No such file or directory
ls: cannot access /scratch3/NCEPDEV/swpc/noscrub/Adam.Kubaryk/ICS/WAM-IPE/2013031600/ipe_grid_*_params*201303190000: No such file or directory
   can't find your IPE files... check the filename convention! exiting.
```

When trying `./submit.sh march2013_regression.config 2 5`, I get the same thing. Can this be corrected ?

**Comment by akubaryk** [comment]
Unfortunately this is the intended behavior of the system. Because WAM and IPE have one-way-coupling, WAM is allowed to run ahead of the IPE component. In this case, WAM ran to the completion of its 24 hour cycle, wrote out the restart files (of which only one copy is kept), and afterwards IPE crashed prior to finishing that cycle. In other words, the restart files from the previous cycle are overwritten and cannot be recovered without integrating from the start again.

The only option we have to retain the files is keep separate copies of the restart files, e.g. prefixing in the restart directory with the initialization date for each cycle. Even that is a half-measure: if you have, for example, FHRES=24 and FHMAX=48, WAM could still make it to writing the end-of-cycle restart file. But at least in this scenario we'd only lose one cycle rather than the whole thing?

**Comment by akubaryk** [comment]
As for why the crash happened -- the 8 hour job reached its wallclock limit when the prior 24hr cycles had taken ~2 hours to integrate. Check out the modified dates on these files, for the cycle that crashed:

```
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 18:06 ipe_grid_plasma_params.201303180300
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 18:06 ipe_grid_neutral_params.201303180300
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 18:12 ipe_grid_plasma_params.201303180400
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 18:12 ipe_grid_neutral_params.201303180400
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 18:18 ipe_grid_plasma_params.201303180500
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 18:18 ipe_grid_neutral_params.201303180500
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 18:23 ipe_grid_plasma_params.201303180600
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 18:23 ipe_grid_neutral_params.201303180600
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 18:29 ipe_grid_plasma_params.201303180700
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 18:29 ipe_grid_neutral_params.201303180700
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 20:15 ipe_grid_plasma_params.201303180800
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 20:15 ipe_grid_neutral_params.201303180800
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 27 23:00 ipe_grid_plasma_params.201303180900
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 27 23:00 ipe_grid_neutral_params.201303180900
-rw-r--r-- 1 Joseph.Schoonover stmp  227911808 Mar 28 01:11 ipe_grid_plasma_params.201303181000
-rw-r--r-- 1 Joseph.Schoonover stmp  424592040 Mar 28 01:11 ipe_grid_neutral_params.201303181000
```
So they were going at 5-6 minutes per hour like normal, and then suddenly jumped to ~2 hours per hour. Looking at an example PET file for IPE during the normal period (prior to 2013031807): 
```
20180327 222816.798 INFO             PET403 >>>IPM entered Run (phase=RunPhase1) with current time: 2013  3 18  6 51  0   0
20180327 222816.798 INFO             PET403 sub-update_IPE start:
20180327 222816.798 INFO             PET403 sub-update_IPE neutral:
20180327 222816.857 INFO             PET403 sub-update_IPE eldyn:
20180327 222816.891 INFO             PET403 sub-update_IPE plasma:
20180327 222821.818 INFO             PET403 sub-update_IPE eldyn:
20180327 222821.852 INFO             PET403 sub-update_IPE plasma:
20180327 222826.391 INFO             PET403 sub-update_IPE eldyn:
20180327 222826.426 INFO             PET403 sub-update_IPE plasma:
20180327 222830.910 INFO             PET403 sub-update_IPE output:
20180327 222830.910 INFO             PET403 sub-update_IPE finished:
20180327 222830.910 INFO             PET403 IPM time stepping loop, current time: 2013  3 18  6 54  0   0
20180327 222830.910 INFO             PET403 <<<IPM leaving Run (phase=RunPhase1) with current time: 2013  3 18  6 54  0   0
```
Showing a timestep of about 15 seconds for 3 minutes, which is in line with 2hrs wallclock for 24hrs integration. But then when things were very slow:
```
20180328 004601.141 INFO             PET403 >>>IPM entered Run (phase=RunPhase1) with current time: 2013  3 18  8  9  0   0
20180328 004601.141 INFO             PET403 sub-update_IPE start:
20180328 004601.141 INFO             PET403 sub-update_IPE neutral:
20180328 004601.200 INFO             PET403 sub-update_IPE eldyn:
20180328 004601.235 INFO             PET403 sub-update_IPE plasma:
20180328 004859.621 INFO             PET403 sub-update_IPE eldyn:
20180328 004859.656 INFO             PET403 sub-update_IPE plasma:
20180328 005153.471 INFO             PET403 sub-update_IPE eldyn:
20180328 005153.505 INFO             PET403 sub-update_IPE plasma:
20180328 005452.560 INFO             PET403 sub-update_IPE output:
20180328 005452.560 INFO             PET403 sub-update_IPE finished:
20180328 005452.560 INFO             PET403 IPM time stepping loop, current time: 2013  3 18  8 12  0   0
20180328 005452.560 INFO             PET403 <<<IPM leaving Run (phase=RunPhase1) with current time: 2013  3 18  8 12  0   0
```
About 14 minutes for 3 minutes of integration. It's hard to tell if these were related to Theia or some kind of issue with slow convergence in the FLIP solver, since FLIP_ERR doesn't contain timestamps of any kind.

Do we have 5-day runs with development? Have a feeling this is something that would show up as of the raw_high_lat merge, and not necessarily an issue with fixed geomagnetic and solar wind inputs.

**Comment by joeschoonover** [comment]
We don't have a 5 day with development, but I've run into a similar issue with PR #155 .

**Comment by joeschoonover** [comment]
## Initial Conditions (March 16, 2013, 00UT)
tec 201303160000
thermospheretemperature 201303160000

## Day 2 ( March 17, 2013, 00UT )
tec 201303170000
thermospheretemperature 201303170000

## TEC Around Model Slowdown
tec 201303180900

**Comment by joeschoonover** [comment]
For reference, V0.4.1 runs without issue through more than 10 days. With fewer processors (80 for IPE, compared to the 464 we're now using), we can get 5 days in under 8 hours wall time. 

Tip of development experiences a similar problem to what we're seeing here.

**Comment by joeschoonover** [comment]
With this being said, I'm ok with approving this pull request, since this branch is not responsible for bringing in new problems.

**Comment by joeschoonover** [comment]
@twfang @timfullerrowell , please provide a review on the model output for this pull request; if there are additional model outputs you want to see, this is the time to request them

**Comment by joeschoonover** [comment]
I should point out that this run is using fixed drivers in WAM and IPE

**Comment by joeschoonover** [comment]
@twfang, how close are we to merging this branch into development ?

**Comment by twfang** [comment]
I think we can get this branch merge today. I have tested all the switches for different drivers and looked through their numbers for CDATE=20130316. The WAM standalone would run through 5-day test without any problems. The restart problem remains in this branch. The coupled WAM-IPE run would still hang after 2 days. 

We need to run the model with the user.config file instead of march2013_regression.config to have the capability of setting different drivers. The CDATE in user.config should probably be set for 20130316 instead of its current default value (i.e. 20150317) to be compatible with our other branches and tests.

**Pull request merged**
