### PR TITLE
Bring in new_restart_files into development

### PR DESCRIPTION
**Pull request by joeschoonover**
The new_restart_files branch contains changes to the WAM code base that help resolve Issue #33 . Particularly, we carried over changes from the WAM SVN repository to calculate the vertical velocity in WAM at the first time step before calling the mediator to pass the neutral fields to IPE.

Each assignee and reviewer should verify that the restart bug is fixed.

In issue #33, I have already verified that a 1hr+1hr restart and a 2hr simulation produce bitwise identical results.

### CODE REVIEW

**Comment by joeschoonover** [comment]
## In need of one developer to verify results !
@twfang @rmontuoro @gmillward @oehmke @ZhuxiaoLi0113 
I've resolved merge conflicts between development and new_restart_files ( see commit 8bb404906ef6e492e802d41493210d7afabe1d39 for more details )

I'm currently verifying that 1hr + 1hr and 2hr simulations are bit-for-bit identical and I need one other person to volunteer to do this as well. @akubaryk , as reviewer, once you see that we have two confirmed results that indicate resolution of Issue #33 , please submit your review.

To do this test, download the latest version of the new_restart_files branch. Either make a new branch locally 
```
git checkout origin/new_restart_files -b new_restart_files
```
or update an existing local copy of new_restart_files
```
git checkout new_restart_files
git pull
```

Rebuild the source code from scratch
```
NEMS/NEMSAppBuilder rebuild app=wam-ipe
```

To submit the either simulation, once compilation is done, go into the `scripts/compsets/` directory.

## To run the 1hr + 1hr simulation
* Open the march2013_regression.config file in  a text editor.
* Change the `JOBNAME` to `march2013_1hr_1hr`
* Verify that `FHMAX=1`
* Submit the 1hr + 1hr restart using the command
```
./submit.sh march2013_regression.config 1 2
```
`/scratch4/NCEPDEV/stmp3/${USER}/march2013_1h_1hr/`
## To run the 2hr simulation
* Open the march2013_regression.config file in  a text editor.
* Change the `JOBNAME` to `march2013_2hr`
* Verify that `FHMAX=2`
* Submit the 2hr restart using the command
```
./submit.sh march2013_regression.config 1 1
```
This will give you model output under `/scratch4/NCEPDEV/stmp3/${USER}/march2013_2hr/`

After running both simulations, do
```
diff -q /scratch4/NCEPDEV/stmp3/${USER}/march2013_2hr/ /scratch4/NCEPDEV/stmp3/${USER}/march2013_1hr_1hr/
```
to compare model results. If everything is successful, only differences in the `fcst.*` files should be reported. *Copy the output of the `diff` command to this pull request to prove that bit-for-bit results are obtained*

**Comment by ZhuxiaoLi0113** [comment]
I am doing this.

**Comment by joeschoonover** [comment]
Thanks @ZhuxiaoLi0113 . Everyone else, you're off the hook

**Comment by joeschoonover** [comment]
Here's the diff output from my runs : 
```
[Joseph.Schoonover@tfe08 compsets]$ diff -q /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_1hr_1hr/ /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_2hr/
Only in /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_1hr_1hr/: fcst.30168447.bqs3
Only in /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_1hr_1hr/: fcst.30168511.bqs3
Only in /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_2hr/: fcst.30168670.bqs3
Common subdirectories: /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_1hr_1hr/restart_directory and /scratch4/NCEPDEV/stmp3/Joseph.Schoonover/march2013_2hr/restart_directory
```

**Comment by ZhuxiaoLi0113** [comment]
Joe, I got the same diff output from my runs also as following:
Only in march2013_2hr: fcst.30169731.bqs3
Only in march2013_1hr_1hr_new: fcst.30170087.bqs3
Only in march2013_1hr_1hr_new: fcst.30170123.bqs3
Common subdirectories: march2013_1hr_1hr_new/restart_directory and march2013_2hr/restart_directory

**Comment by joeschoonover** [comment]
@akubaryk can you approve this request ?

**Pull request merged**
