### PR TITLE
SLURM scheduler on Theia

### PR DESCRIPTION
**Pull request by akubaryk**
Theia is changing from PBS to SLURM job scheduling in early May. All of the commonly used scripts (`scripts/compsets`, `scripts/ipe_io_convert`, and `scripts/plot`) were ported and tested, and the less commonly used/unsupported scripts (OldCompsetRun notably) were ported without testing.

If there are any other scripts that people need ported in the repository, or if any issues are uncovered, please let me know so the issues can be addressed ASAP -- the clock is ticking on this now, but it should be mostly transparent to end users except for the following:

People should add `module load slurm` to their .bashrc or .cshrc file on Theia so the new scheduler aliases and executables are added to your PATH. This may not be necessary once the full changeover occurs. `sbatch` replaces `qsub`, `squeue` replaces `qstat`, `scancel` replaces `qdel`, and **`srun` replaces `mpirun` and/or `mpiexec`**. Some additional useful information on transitioning from PBS to SLURM can be found [here](https://docs.google.com/spreadsheets/d/1h3PHJPZzlQsBqBNvG6gjIuuItUH4il1s-IJaXoAqSGA/edit#gid=0) or [here](https://hpc.nih.gov/docs/pbs2slurm.html). If you are interested in a more complete overview, the SLURM training slides are available [here](https://docs.google.com/presentation/d/1EzbB_VFfN7FLcp2Q4gvbGxJqYTB5vGW3VniwZu_Znsw/edit#slide=id.g523983a6c2_0_0).

### CODE REVIEW

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi @akubaryk,

thank you very much for taking the initiatives on transitioning to slurm.
in testing your scripts, I would like to compare 2 runs: before and after your changes. What is the "before" hashID?
 

Hi reviewers, @rmontuoro , @ZhuxiaoLi66 , @joeschoonover ,
  shall we try to coordinate our testing tasks? which scripts do you want to test?
  I am going to test scripts/ipe_io_convert

**Comment by akubaryk** [comment]
Can use the development branch as the before hash id, this is only one commit so the hash id is f91f1cbc273393567844f1fadc67e13582c2b21e

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Thanks, @akubaryk !

I started the reference run with hash id is f91f1cb
I would like to share with you if anybody is interested to compare to your test runs.

WAM-IPE src code:
/scratch3/NCEPDEV/stmp1/Naomi.Maruyama/tmp/WAM-IPE/

wam-ipe run setting:
date: 20130316
duration: 1hr
INPUT_PARAMETERS=fixall

rundirectory:
/scratch4/NCEPDEV/stmp3/Naomi.Maruyama/issue_291/
/scratch4/NCEPDEV/stmp4/Naomi.Maruyama/issue_291/

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi  @akubaryk 

I tested the wam-ipe script, by 
$./submit.sh coupled_20130316.config

b4b was confirmed by comparing the ipe original output(ipe_grid_plasma_params.20130316) between before (f91f1cb ) and after your changes.

my next task is to test scripts/ipe_io_convert .

**Comment by akubaryk** [comment]
So ipe_io_convert was in use for changing the plasma_* and neutral_* files into the consolidated files we use now, and with the transition to the refactor we can probably abandon that script since it'll be two generations out of date at that point, but you're welcome to test it if you have some old initial conditions sitting around.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Hi @akubaryk 

I got confused between scripts/ipe_io_convert vs. IPELIB/scripts/Convert_mpi.batch. I am sorry.
Does Convert_mpi.batch need a separate test because it includes "qsub"? It is initiated by submit.sh.
Thanks.

**Comment by akubaryk** [comment]
So that script has been converted to SLURM, but you should definitely try it out. Because it is run with `./Convert_mpi.batch` there's no user-facing change to that one; the new script submits a temporary job with sbatch instead of qsub.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk I checkout the slurm branch and recompiled, did a 1 day WAM stand along run and compared the run by the development tip version, got bit by bit output, the only concern now is that scripts/compsets/march2013_regression.config didn't change from the dep_tip run, it is supposed change, right? talk later.  
will recompile from the scratch again and redo the run and approving review tomorrow.

**Comment by ZhuxiaoLi66** [comment]
don't see the reason that scripts/compsets/march2013_regression.config need to be changed.
will confirm with you tomorrow.

**Comment by ZhuxiaoLi66** [comment]
The output from slurm has been verified after recompile the branch. 
My output directories for slurm and development runs:
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/slurm_fix_0301_1day
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/slurm_fix_0301_1day
Codes directories:
/scratch3/NCEPDEV/swpc/save/Zhuxiao.Li/git/WAM-IPE_slurm
/scratch3/NCEPDEV/swpc/save/Zhuxiao.Li/git/WAM-IPE_dev_tip

@akubaryk I didn't find neither qsub or sbatch in ./scripts/compsets/submit.sh. 
I found significant difference between ./scripts/compsets/config/theia.config in the two versions, 
also some other config files as your branch shows.

**Comment by akubaryk** [comment]
Yes, the fact that qsub/sbatch is not in submit.sh was a function of intentional design -- all of the machine-specific code, including job scheduler setup, is in the $MACHINE.config files, so only theia.config needed to be changed for my run scripts. The change to the march2013_regression.config is only to set MODE=standaloneWAM... I did not mean to commit that change, but I don't feel it's a big deal since it is just a template file for users to work from. Can definitely revert if the group prefers though.

**Pull request merged**
