### PR TITLE
Eddy heat condT3

### PR DESCRIPTION
**Pull request by ZhuxiaoLi66**
The new physics scheme eddy_heat_condT completes the calculation of neutral temp. tendency in idea_dissipation.f of WAM by including the influence of eddy heat conductivity process on it besides the original influence of molecular conductivity process. The high level temp. is cooling down by the eddy mixing process which peaks at around 105km by less than 100 degrees, more in storm run, which solved the problem that there is over heating globally in current WAM run with the driving of high frequency Space Weather Parameters.

Please see issue #180 for its develop and validation history.

### CODE REVIEW

**Comment by twfang** [comment]
Few updates, 

1. 10-day WAM standalone run has been carried out. Few plots need to be made to validate the changes. 

2. 5-day WAM-IPE run with fixed drivers finished without problem. Ionospheric parameters from the results look good. 

3. Some cleaning of the code is required before being committed back to the development branch. I will communicate with Zhuxiao on this.

**Comment by ZhuxiaoLi66** [comment]
The comparison between the condT_test pull request WAM run and the original WAM standalone run is indicated in the following plots. The Temp. tendency looks good except slight difference. 
    
global_mean_t_condt_l150_2keddy_msis_0301_15day_tzu-wei
global_mean_t_condt_l150_2keddy_msis_0301_15day

**Comment by ZhuxiaoLi66** [comment]
the Temp. profiles by WAM-IPE with new eddy_heat_condT and new IC file (2013031600). 
global_mean_t_condt_l150_2keddy_msis_0316_5day_wam-ipe_tzu-wei

**Comment by ZhuxiaoLi66** [comment]
results looks pretty good.

**Comment by twfang** [comment]
Thanks @ZhuxiaoLi66  for the plots. The 5-day WAM-IPE run finished successfully. Ionosphere TEC looks good. We are ready to bring the changes into development branch.

**Comment by ZhuxiaoLi66** [comment]
We have got the bit-by-bit identical outputs between the original eddy_heat_condT3 branch and its merged version with development (pull request version),  after we reverse the NEMS part to 50512c7 in its pull request version,  that means for eddy_heat_condT3 branch:

Current pull request version=  NEMS( original eddy_heat_condT3 branch before merge) + All other parts (tip development branch)

**Comment by joeschoonover** [comment]
With @ZhuxiaoLi66 's laterst changes, can we get a review on this @twfang so that the pull request can be closed ?

**Comment by twfang** [comment]
@ZhuxiaoLi66 I have tested your version with a 20-day WAM run. Could you please take a look at the output and let me know if everything looks good? I will do a few WAM-IPE run before we close it. 

My files are located at:/scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/WAM-eddy

**Comment by ZhuxiaoLi66** [comment]
@Tzu-Wei I will take a look at your run results after get to office. Would like you know that I am taking time off now and hopefully can get back to office a couple of hours this afternoon ( maybe I can't attend the developer meeting this afternoon).  
As for the temporary code validation idea for WAM, I think the most important thing is get the bit-by-bit results with the control one at first. So if you still keep my directories for the former runs, please check that at first.  Let us talk the runs later.

**Comment by twfang** [comment]
I have tested stand-alone WAM, coupled WAM-IPE with fixed drivers and time-varying drivers. The stand-alone run results are bit-by-bit the same as Zhuxiao's previous results. The coupled WAM-IPE run with fixed drivers shows reasonable ionosphere. The WAM-IPE run with time-varying driver, however, didn't finish successfully. But the crash symptoms are similar to previous WAM-IPE behaviors. Therefore, I believe we are ready to merge the branch into development branch.

**Pull request merged**
