### PR TITLE
Transport fix ghgm dev

### PR DESCRIPTION
**Pull request by joeschoonover**
Carries over the fixes of the high latitude transport plus removal of an excessive amount of write statements.

### CODE REVIEW

**Comment by joeschoonover** [comment]
@gmillward , I'll do a quick run with your code to make sure all looks good. Once I've checked model output, I'll work on getting this in

**Comment by joeschoonover** [comment]
I ran a day with fixed drivers and all looks good there. @twfang can we open a new issue for this particular bug you're mentioning and merge this branch in ?

**Comment by joeschoonover** [comment]
Only modification I request is that 

`march2013_regression.config-george` be removed and
`march2013_regression.config` is updated to include this block : 
```
## FIXED INPUT PARAMETERS
# INPUT_PARAMETERS options (default: timederive, FIX_F107=120.0, FIX_KP=3.0):
# timeobs    - read all geomagnetic and solar input parameters from database files
# timederive - read from database for F10.7, F10.7d, Kp, and 24h Avg Kp; derive solar wind parameters from F10.7/Kp
# fixderive  - specify constant F10.7 (used for F10.7d) and Kp (used for 24h Avg Kp); derive as above
# fixall     - fix all fields
# realtime   - read from the .xml data if available, or use wam_input_f107_kp.txt provided in IC_DIR otherwise
export INPUT_PARAMETERS=fixderive
## if you are using fixderive or fixall, uncomment the following and set your fixed values
export FIX_F107=120.0     # F10.7 and F10.7d
export FIX_KP=3.0         # Kp and 24hr average Kp
# export FIX_SWBT=1.0       # total solar wind
# export FIX_SWANG=0.0      # solar wind angle
# export FIX_SWVEL=400.0    # solar wind velocity
# export FIX_SWBZ=1.0       # z-component of solar wind
# export FIX_GWATTS=4.5     # gigawatts
# export FIX_HPI=2          # hemispheric power index
```
at the bottom of the script

**Comment by joeschoonover** [comment]
@twfang , when you can, submit your review when you can

**Comment by joeschoonover** [comment]
Just committed those changes

**Comment by twfang** [comment]
@gmillward I found out the the lpmin_perp_trans in your exglobal_fcst_nems.sh is still set to 15. You would need to change it to 1 since the current code should work all the way to the pole. I did have it changed in my ipe_transport_fix branch. 

I have download the code and will do a test run before I approve the pull request.

**Comment by twfang** [comment]
Hey guys, I am not able to compile the code from this branch? The problem seems to be in WAM. Do you have any problems compiling?

**Comment by akubaryk** [comment]
@oehmke noted yesterday that the nemsio module includes were throwing up errors. I have an inkling that the location of those files has changed...

**Comment by joeschoonover** [comment]
@akubaryk is NEMS_IO being brought in through a "module load" ?

**Comment by twfang** [comment]
Yes, please change it. Once you guys figure the compiling issues, I will run the code with the change. Thanks!

**Comment by joeschoonover** [comment]
@twfang just pushed up a commit with this fix in exglobal_fcst_nems.sh

**Comment by joeschoonover** [comment]
Submitting for a multi-day run on this branch. Provided the output looks ok, we'll need someone to approve this PR

**Comment by joeschoonover** [comment]
5 day run looks good. @twfang can you submit a review ?

**Pull request merged**
