### PR TITLE
Mdate compatible timestamp

### PR DESCRIPTION
**Pull request by akubaryk**
Once again, a large diff because I ran make clean from NEMS/src and don't have all of the NEMS .f90 files in my branch, but the primary changes are to the IPELIB/IPE Cap to change the timestamp to remove the T (dropping the string length from 13 to 12), and then adding a first revision of my compset scripts. Before this pull request gets merged in, we should be sure that all of the plotting scripts are all able to handle the new timestamp format.

### CODE REVIEW

**Comment by joeschoonover** [comment]
The plotting convert and plotting programs function with the new time stamp format. If all checks out on WCOSS and theia from your end in terms of compiling and running, go ahead and merge the pull request and delete the branch

**Comment by joeschoonover** [comment]
Why are there so many .f90 files that are deleted ?

**Comment by akubaryk** [comment]
Part of the compile process does pre-processing in the NEMS src that takes all the .f and .F files and makes them .f90 and .F90. They're not a part of the actual source tree since they are generated by the build system, so they should probably be wiped out or ignored in .gitignore or something?

**Comment by joeschoonover** [comment]
Yea. We'll have to get a list of those files, add to the gitignore and remove them from the repository

**Comment by akubaryk** [comment]
This is now also prepped for Raffaele's changes to domain decomposition with SMS. Going to merge this pull request and delete the branch, as the only significant changes are to the timestamp (has been verified to not be an issue), while my new compset scripts are optional, and documentation is en route.

**Pull request merged**
