### PR TITLE
Update of new_restart_files from development

### PR DESCRIPTION
**Pull request by joeschoonover**
We need to keep the new_restart_files branch up to date with development to prevent more difficulties down the road.

Recall that the new_restart_files branch is needed to help resolve Issue #33 

Currently, there are merge conflicts with the following files : 

NEMS/src/module_MEDIATOR_SpaceWeather.F90 ( @oehmke or @rmontuoro please review this file )

NEMS/src/atmos/phys/idea_tracer.f ( @ZhuxiaoLi0113 please review this file )

IPE/module_update_IPE.F90 (@joeschoonover please review this file)

I've assigned people that I think are appropriate for each file.

If you like, we can resolve this pull request at our next developer meeting.

### CODE REVIEW

**Comment by joeschoonover** [comment]
Remarks from @rmontuoro relayed from Slack 
"... the conflicts in `NEMS/src/module_MEDIATOR_SpaceWeather.F90` and I'm a bit confused. I tried to replicate the merge and fix the conflicts in my local repository, but some important portions of the mediator source code in the *development* branch did not get merged. I'd recommend using the current version of the `NEMS/src/module_MEDIATOR_SpaceWeather.F90` file in the merged branch. "

**Comment by joeschoonover** [comment]
@rmontuoro , are you suggesting that we use the version of `module_MEDIATOR_SpaceWeather.F90` from the tip of the new_restart_files in the development branch ?

**Comment by rmontuoro** [comment]
@joeschoonover, I'm suggesting that we use the version of `module_MEDIATOR_SpaceWeather.F90` in the tip of the `development` branch.

**Comment by rmontuoro** [comment]
The tip of `new_restart_files` builds successfully after changes from the development branch were brought in. However, it fails at runtime with the following error:
```forrtl: severe (19): invalid reference to variable in NAMELIST input, unit 35, file /scratch4/NCEPDEV/stmp4/Raffaele.Montuoro/march2013/atm_namelist, line 2, position 34```

**Pull request merged**
